### ISSUE TITLE
Use the standard ZE container config test suite

### ISSUE THREAD

**Issue by gdsmith** [elie29/zend-di-config#18]
This implementation doesn't pass all the tests from the [config test suite](https://github.com/zendframework/zend-container-config-test). I added it locally and it fails the tests.

**Comment by elie29** [comment]
Thank you for this issue. I didn't provide all keys from the service manager [configuration](https://docs.zendframework.com/zend-servicemanager/configuring-the-service-manager/).
However, you are welcome to enhance the implementation.

**Comment by elie29** [comment]
I added the config test suite. In the creation method you need to add dependencies key to your $config.
Second, as we are using autowire technique, the invalid tests won't be correct, because the container would resolve automatically the object, as per example, [Delegator.class](https://github.com/zendframework/zend-container-config-test/blob/master/src/InvokableTestTrait.php#L75).

However, I figured out that invokables should be an array of services as well as key/name array and when the key is different than the name, we should aliased the name. I will create an issue for that, and do not hesitate to create more issues.

thx @gdsmith !
